<?php
/* --------------------------------------------------------------
   afterbuy.lang.inc.php 2023-04-28
   Gambio GmbH
   http://www.gambio.de
   Copyright (c) 2023 Gambio GmbH
   Released under the GNU General Public License (Version 2)
   [http://www.gnu.org/licenses/gpl-2.0.html]
   --------------------------------------------------------------
*/

$t_language_text_section_content_array = [
    'account_token'                            => 'Account Token',
    'account_token_tooltip'                    => 'Your Account-Token for the Afterbuy XML Interface',
    'afterbuy_order_id'                        => 'Afterbuy Order ID',
    'all_as_not_paid'                          => '(treat all others as not paid)',
    'all_as_paid'                              => '(treat all as paid)',
    'button_send'                              => 'send to Afterbuy',
    'config_xml_api'                           => 'API credentials',
    'configuration'                            => 'Configuration',
    'configuration_orderexport'                => 'Orders export',
    'configuration_shop_api'                   => 'Send Orders (Shop API)',
    'cron_note'                                => 'Cronjob',
    'cron_note_text'                           => 'Please activate the Afterbuy Synchronization task at Toolbox → Scheduled Tasks to enable periodic transmissions of orders. The old cronjob URL used in previous version does not need to be called any more.',
    'cron_url'                                 => 'Cron job URL',
    'cron_url_tooltip'                         => 'To trigger data transfer to Afterbuy, please configure a cron job to call this URL regularly.',
    'datetime'                                 => 'Time',
    'do_not_change'                            => '(do not change)',
    'do_not_set'                               => '(do not set)',
    'extent_of_import'                         => 'Extents of import',
    'import_catalogs'                          => 'Import catalogs',
    'import_catalogs_now'                      => 'Import catalogs now',
    'import_catalogs_parent_category'          => 'Import catalogs into this category',
    'import_catalogs_tooltip'                  => 'Import Afterbuy catalogs into categories now and update existing categories.',
    'import_configuration'                     => 'Configuration for data import',
    'import_in_progress'                       => 'Import in progress',
    'import_mode_products_import'              => 'Import products',
    'import_mode_stocksync'                    => 'Stock synchronization',
    'import_operations'                        => 'Import operations',
    'import_products'                          => 'Import products',
    'import_products_dealer_group'             => 'Customer group for dealer prices',
    'import_products_default_category'         => 'Default category for products import',
    'import_products_default_category_tooltip' => 'Products will be imported into this category if they are not linked to a catalog or the catalog has no corresponding category.',
    'import_products_dont_import'              => 'do not import',
    'import_products_level_threshold'          => 'Upper level for active products',
    'import_products_level_threshold_tooltip'  => 'Products with a level above this threshold will be imported as inactive.',
    'import_products_now'                      => 'Import products now',
    'import_products_restart'                  => 'Reset timestamp',
    'import_products_tooltip'                  => 'Importing new and modified products normally runs as a background task (cf. Scheduled tasks). You can use the button here to start/continue a complete run.',
    'import_starting_from_timestamp'           => 'Import products modified since',
    'import_tax_class_1'                       => 'Tax class 1',
    'import_tax_class_2'                       => 'Tax class 2',
    'import_tax_class_3'                       => 'Tax class 3',
    'import_tax_class_4'                       => 'Tax class 4',
    'import_tax_class_5'                       => 'Tax class 5',
    'last_sync_datetime'                       => 'Changes since',
    'last_sync_datetime_tooltip'               => 'For the next synchronization of product quantities, products changed after this point will be considered. This value is updated automatically by the synchronization process.',
    'last_tracking_sync_tooltip'               => 'For the next synchronization of orders quantities, products changed after this point will be considered. This value is updated automatically by the synchronization process.',
    'logging_level'                            => 'Logging level',
    'logging_level_debug'                      => 'debug – very verbose',
    'logging_level_error'                      => 'error – errors only',
    'logging_level_info'                       => 'info – normal events',
    'logging_level_notice'                     => 'notice – significant events',
    'logging_level_warning'                    => 'warning – problematic events',
    'missing_order_id'                         => 'Missing order id must be provided',
    'module_active'                            => 'active',
    'order_info_heading'                       => 'Afterbuy',
    'order_info_id'                            => 'Afterbuy Customer ID',
    'order_info_success'                       => 'Data successfully transmitted',
    'order_info_success_no'                    => 'no',
    'order_info_success_yes'                   => 'yes',
    'order_status'                             => 'Order status after transmission',
    'order_status_after_tracking_sync_label'   => 'Order status after tracking-code sync in Afterbuy',
    'order_status_after_tracking_sync_tooltip' => 'If a shipping tracking ID is found in an order during order matching, the order is set to the selected order status in the shop',
    'order_status_not_paid'                    => 'Order status (not paid order)',
    'order_status_not_paid_tooltip'            => 'Order status which mark a not paid order',
    'order_status_paid'                        => 'Order status (paid order)',
    'order_status_paid_tooltip'                => 'Order status which mark a fully paid order',
    'order_status_set_delivery_date_label'     => 'Set shipping date based on order status',
    'order_status_set_delivery_date_tooltip'   => 'When exporting orders, the system checks whether the selected order status occurs in the order status history and if it does, it sets the shipping date at the time of setting the order status.',
    'order_status_tooltip'                     => 'Order status after successful transmission of order data',
    'partner_id'                               => 'Partner ID',
    'partner_id_tooltip'                       => 'Your Afterbuy Partner ID',
    'partner_password'                         => 'Partner Password',
    'partner_password_tooltip'                 => 'Your Partner Password for the Afterbuy Shop Interface',
    'partner_token'                            => 'Partner Token',
    'partner_token_tooltip'                    => 'Your Partner Token for the Afterbuy XML Interface',
    'product_data_import_mode'                 => 'Mode for import of products data',
    'product_import_progress'                  => 'Products import',
    'product_import_start'                     => 'Importing products, please wait.',
    'product_import_stop'                      => 'Stop',
    'product_import_stopping'                  => 'Stopping …',
    'product_sync_model_anr'                   => 'Product Model (Shop) = article number (Afterbuy)',
    'product_sync_model_ean'                   => 'Product Model (Shop) = external article number (Afterbuy)',
    'product_sync_model_prodid'                => 'Product Model (Shop) = ProductId (Afterbuy)',
    'product_sync_pid_anr'                     => 'ProductID (Shop) = article number (Afterbuy)',
    'product_sync_pid_ean'                     => 'ProductID (Shop) = external article number (Afterbuy)',
    'product_sync_type'                        => 'Product sync type',
    'product_sync_type_tooltip'                => 'How are correlating product entries in the shop and at Afterbuy identified? Please make sure the values are unambiguous!',
    'quantity_sync'                            => 'Product quantity synchronization',
    'quantity_sync_info'                       => 'Product quantities can be updated with values from Afterbuy at regular intervals. In order to activate this feature please enable the Cronjob at Toolbox → Scheduled Tasks. Please note: For the quantities synchronization to work your products in the shop and at Afterbuy must adhere to the product sync type configured above. Products with Additional Options cannot be synchronized. Do not use together with product import.',
    'save_configuration'                       => 'save',
    'send_order_details'                       => 'Send order details',
    'send_shipping_info'                       => 'Send shipping method',
    'send_shipping_info_never'                 => 'never',
    'send_shipping_info_initially'             => 'initially',
    'send_shipping_info_always'                => 'always',
    'send_shipping_info_tooltip'               => 'Send shipping method as chosen by customer in checkout.',
    'sent_initial'                             => 'The order has been successfully transferred to Afterbuy.',
    'sent_successfully'                        => 'Order data sent successfully.',
    'sent_unsuccessfully'                      => 'Error sending order data:',
    'sent_update'                              => 'The order has been successfully updated in Afterbuy.',
    'stocksync_configuration'                  => 'Configuration of stock synchronization',
    'tracking_sync_description'                => 'Shipping method registered with Afterbuy',
    'tracking_sync_free_text_placeholder'      => 'Afterbuy shipping',
    'tracking_sync_label'                      => 'Shop parcel service',
    'tracking_sync_tooltip'                    => 'If a tracking number is stored in the Afterbuy order and the shipping method corresponds to the value of the free field, a tracking link is generated in the shop when synchronizing the orders.',
    'unauthenticated'                          => 'Unauthenticated!',
    'unknown_order_status'                     => 'Order was not transferred, order status does not correspond to either paid or unpaid status.',
    'update_quantities'                        => 'Update product quantities',
    'update_quantities_now'                    => 'Update quantities now',
    'update_quantities_tooltip'                => 'Updates products quantities based on orders registered at Afterbuy after the timestamp configured above.',
    'use_correctional_items'                   => 'Use correctional items',
    'use_correctional_items_tooltip'           => 'Different strategies for rounding can cause differences between invoice amount and payment amount at Afterbuy. This option enable the use of additional correctional items to alleviate this.',
    'use_separate_tax'                         => 'Use separate items for VAT (B2B)',
    'use_separate_tax_tooltip'                 => 'For B2B orders with separate VAT the taxes will be exported as separate items, not as part of the regular items.',
    'user_id'                                  => 'User ID',
    'user_id_tooltip'                          => 'Your Afterbuy User ID',
];
