<?php
/* --------------------------------------------------------------
	internetmarke.lang.inc.php 2019-04-11
	Gambio GmbH
	http://www.gambio.de
	Copyright (c) 2015 Gambio GmbH
	Released under the GNU General Public License (Version 2)
	[http://www.gnu.org/licenses/gpl-2.0.html]
	--------------------------------------------------------------
*/

$t_language_text_section_content_array = [
    'actual_ppl_version'                  => 'PL version',
    'clear_cache'                         => 'update products and prices',
    'configuration_heading'               => 'Internet Stamp Configuration',
    'configuration_saved'                 => 'Configuration saved',
    'create_another_voucher'              => 'buy another stamp',
    'create_label'                        => 'create Internet Stamp',
    'create_label_window_title'           => 'Internet Stamps',
    'create_voucher'                      => 'buy stamp',
    'credentials'                         => 'Credentials',
    'do_not_change'                       => 'do not change',
    'error_credentials_invalid'           => 'Entered credentials are invalid.',
    'error_invalidmotive'                 => 'Invalid motive.',
    'error_invalidorderpositioncount'     => 'Invalid order position count.',
    'error_invalidpageformat'             => 'Invalid page format',
    'error_invalidproductcode'            => 'Invalid product code',
    'error_invalidshoporderid'            => 'Invalid ShopOrderID',
    'error_invalidtotalamount'            => 'Invalid total amount',
    'error_invaliduser'                   => 'Invalid user account',
    'error_walletbalancenotenough'        => 'Insufficient funds in postage wallet',
    'error_walletnotavailable'            => 'No usable postage wallet available',
    'first_ppl_version'                   => 'first PPL version',
    'image'                               => 'Image',
    'internetmarke_module_description'    => 'Create Internet Stamps with Deutsche Post',
    'internetmarke_module_title'          => 'Internetmarke',
    'label_created'                       => 'Label created',
    'label_receiver_additional'           => 'Additional',
    'label_receiver_city'                 => 'City',
    'label_receiver_company'              => 'Company',
    'label_receiver_country'              => 'Country',
    'label_receiver_firstname'            => 'First name',
    'label_receiver_houseno'              => 'House no.',
    'label_receiver_lastname'             => 'Last name',
    'label_receiver_street'               => 'Street',
    'label_receiver_zip'                  => 'Postal code',
    'labels'                              => 'Stamps',
    'last_ppl_version'                    => 'last PPL version',
    'not_available'                       => 'not available',
    'note_credentials_are_optional'       => 'If one or both fields is left empty you will be prompted to log in when necessary. Your credentials will be saved for the duration of the session in that case.',
    'note_session_credentials'            => 'Please enter your credentials. They will be used for the duration of this session.',
    'notify_customer'                     => 'Send email notification',
    'onec4a_email'                        => 'Internet Stamps email',
    'onec4a_key'                          => 'Internet Stamps Key',
    'onec4a_key_phase'                    => 'Internet Stamps Key Phase',
    'onec4a_password'                     => 'Internet Stamps password',
    'order_status_after_label'            => 'Order status after label creation',
    'page_format'                         => 'Page format',
    'parcelservice_id'                    => 'Tracking Link Template',
    'parcelservice_none'                  => 'Do not use tracking',
    'position_labelx'                     => 'Column',
    'position_labely'                     => 'Row',
    'position_on_page'                    => 'Position on page',
    'position_page'                       => 'Page',
    'ppl_date'                            => 'PPL date',
    'ppl_favorite'                        => 'Favorite',
    'ppl_price'                           => 'Price list/contract',
    'ppl_product_name'                    => 'product name',
    'ppl_product_release'                 => 'product release',
    'ppl_product_valid_from'              => 'valid from',
    'preferences'                         => 'Preferences',
    'product'                             => 'Product',
    'products_cache'                      => 'products price list (PPL)',
    'prodws_password'                     => 'Products Web Service password',
    'prodws_user'                         => 'Products Web Service user name',
    'receiver_data'                       => 'Receiver data',
    'save_favorites'                      => 'Save favorites',
    'save_settings'                       => 'Save settings',
    'sender'                              => 'Sender',
    'sender_city'                         => 'City',
    'sender_company'                      => 'Company',
    'sender_country'                      => 'Country',
    'sender_firstname'                    => 'First name',
    'sender_houseno'                      => 'House no.',
    'sender_lastname'                     => 'Last name',
    'sender_street'                       => 'Street',
    'sender_zip'                          => 'Postal code',
    'session_credentials_email'           => 'Email address',
    'session_credentials_password'        => 'password',
    'shipment_data'                       => 'Shipment data',
    'shop_order_id'                       => 'Order ID',
    'show_contract_products_only'         => 'Show contract products only',
    'show_contract_products_only_tooltip' => 'Wenn aktiviert, stehen nur die explizit in Ihrem Vertrag freigeschalteten Produkte bei der Markenerstellung zur Auswahl',
    'show_vouchers'                       => 'Show stamps',
    'submit_error'                        => 'Error in data transmission!',
    'terms_of_service'                    => 'TOS',
    'to_wallet'                           => 'to wallet',
    'tos_read_and_accepted'               => 'I have read and accepted the Allgemeinen Geschäftsbedingungen PORTOKASSE und INTERNETMARKE.',
    'track_id'                            => 'ID for tracking',
    'use_credentials'                     => 'Use credentials',
    'voucher_create_time'                 => 'Create time',
    'voucher_data'                        => 'Product and output',
    'voucher_id'                          => 'Voucher ID',
    'voucher_layout'                      => 'Layout',
    'voucher_layout_addresszone'          => 'Address zone',
    'voucher_layout_frankingzone'         => 'Franking zone',
    'voucher_link'                        => 'Get stamp',
    'vouchers'                            => 'Internet Stamps for this order',
    'wallet'                              => 'Wallet',
    'walletform_info'                     => 'Please click on the button below to tranfer funds to your wallet.',
    'walletform_submit'                   => 'Manage wallet',
    'wallet_balance_too_low'              => 'Your wallet balance is too low.',
    'your_wallet_balance'                 => 'Your balance',
    'low_wallet_balance'                  => 'Assist with low wallet balance',
    'low_wallet_balance_tooltip'          => 'Will prevent purchase of products with prices higher than your current wallet balance. Please deactivate if you use wallet by invoice (balance may be negative).',
];
