<?php
/* --------------------------------------------------------------
	internetmarke.lang.inc.php 2019-04-11
	Gambio GmbH
	http://www.gambio.de
	Copyright (c) 2015 Gambio GmbH
	Released under the GNU General Public License (Version 2)
	[http://www.gnu.org/licenses/gpl-2.0.html]
	--------------------------------------------------------------
*/

$t_language_text_section_content_array = [
    'actual_ppl_version'                  => 'PL-Version',
    'clear_cache'                         => 'Produkte und Preise aktualisieren',
    'configuration_heading'               => 'Internetmarke Konfiguration',
    'configuration_saved'                 => 'Konfiguration gespeichert',
    'create_another_voucher'              => 'Weitere Marke kostenpflichtig drucken',
    'create_label'                        => 'Internetmarke erstellen',
    'create_label_window_title'           => 'Internetmarken',
    'create_voucher'                      => 'Jetzt kostenpflichtig drucken',
    'credentials'                         => 'Login zur Portokasse',
    'do_not_change'                       => 'nicht verändern',
    'error_credentials_invalid'           => 'Die eingegebenen Zugangsdaten sind nicht gültig.',
    'error_invalidmotive'                 => 'Motiv-ID ist ungültig oder nicht bekannt.',
    'error_invalidorderpositioncount'     => 'Die Anzahl der Positionen im Warenkorb übersteigt das zulässige Maximum.',
    'error_invalidpageformat'             => 'Das übergebene Seitenlayout ist nicht bekannt.',
    'error_invalidproductcode'            => 'Das gewählte Produkt ist in der aktuellen Preisliste nicht enthalten.',
    'error_invalidshoporderid'            => 'Die verwendete ShopOrderID ist nicht gültig.',
    'error_invalidtotalamount'            => 'Abweichung zwischen übergebenen und berechneten Gesamtkosten',
    'error_invaliduser'                   => 'Benutzer-Account ist gesperrt',
    'error_walletbalancenotenough'        => 'Das Guthaben Ihrer Portokasse ist nicht ausreichend.',
    'error_walletnotavailable'            => 'Es sind keine einsetzbaren Portokassen verfügbar.',
    'first_ppl_version'                   => 'ab PL-Version',
    'image'                               => 'Motiv',
    'internetmarke_module_description'    => 'Erlaubt das Erstellen von Internetmarken der Deutschen Post',
    'internetmarke_module_title'          => 'Internetmarke',
    'label_created'                       => 'Internetmarke erzeugt',
    'label_receiver_additional'           => 'Adresszusatz',
    'label_receiver_city'                 => 'Stadt',
    'label_receiver_company'              => 'Unternehmen',
    'label_receiver_country'              => 'Land',
    'label_receiver_firstname'            => 'Vorname',
    'label_receiver_houseno'              => 'Hausnummer',
    'label_receiver_lastname'             => 'Nachname',
    'label_receiver_street'               => 'Straße',
    'label_receiver_zip'                  => 'Postleitzahl',
    'labels'                              => 'Marken',
    'last_ppl_version'                    => 'bis PL-Version',
    'not_available'                       => 'n. verf.',
    'note_credentials_are_optional'       => 'Die Hinterlegung der Zugangsdaten für Ihre Portokasse (E-Mail, Passwort) ist optional. Wenn Sie eines oder beide Felder leer lassen, werden die Zugangsdaten bei Bedarf abgefragt und bleiben dann nur für die Dauer der Sitzung gespeichert.',
    'note_session_credentials'            => 'Bitte geben Sie hier Ihre Zugangsdaten für Ihre Portokasse ein. Der Zugang wird für die Dauer der Sitzung verwendet.',
    'notify_customer'                     => 'E-Mail-Benachrichtigung nach Bestellstatusänderung',
    'onec4a_email'                        => 'Internetmarke E-Mail',
    'onec4a_key'                          => 'Internetmarke Key',
    'onec4a_key_phase'                    => 'Internetmarke Key-Phase',
    'onec4a_password'                     => 'Internetmarke Passwort',
    'order_status_after_label'            => 'Bestellstatus nach Labelerzeugung',
    'page_format'                         => 'Seitenformat',
    'parcelservice_id'                    => 'Tracking-Link-Vorlage',
    'parcelservice_none'                  => 'Tracking nicht verwenden',
    'position_labelx'                     => 'Spalte',
    'position_labely'                     => 'Zeile',
    'position_on_page'                    => 'Druckpos.',
    'position_page'                       => 'Seite',
    'ppl_date'                            => 'Stand der Preisliste',
    'ppl_favorite'                        => 'Favorit',
    'ppl_price'                           => 'Preis lt. Liste/Vertrag',
    'ppl_product_name'                    => 'Produktname',
    'ppl_product_release'                 => 'Veröffentlichung',
    'ppl_product_valid_from'              => 'gültig ab',
    'preferences'                         => 'Bevorzugte Einstellungen',
    'product'                             => 'Produkt',
    'products_cache'                      => 'Produktpreisliste (PPL)',
    'prodws_password'                     => 'Produktwebservice Passwort',
    'prodws_user'                         => 'Produktwebservice Benutzer',
    'receiver_data'                       => 'Angaben zum Empfänger',
    'save_favorites'                      => 'Favoriten speichern',
    'save_settings'                       => 'Einstellungen speichern',
    'sender'                              => 'Absender',
    'sender_city'                         => 'Stadt',
    'sender_company'                      => 'Unternehmen',
    'sender_country'                      => 'Land',
    'sender_firstname'                    => 'Vorname',
    'sender_houseno'                      => 'Hausnummer',
    'sender_lastname'                     => 'Nachname',
    'sender_street'                       => 'Straße',
    'sender_zip'                          => 'Postleitzahl',
    'session_credentials_email'           => 'E-Mail-Adresse',
    'session_credentials_password'        => 'Passwort',
    'shipment_data'                       => 'Sendungsdaten',
    'shop_order_id'                       => 'Bestellnummer',
    'show_contract_products_only'         => 'Nur Vertragsprodukte zeigen',
    'show_contract_products_only_tooltip' => 'Wenn aktiviert, stehen nur die explizit in Ihrem Vertrag freigeschalteten Produkte bei der Markenerstellung zur Auswahl',
    'show_vouchers'                       => 'gedruckte Marken anzeigen',
    'submit_error'                        => 'Bei der Übertragung ist ein Fehler aufgetreten!',
    'terms_of_service'                    => 'AGB',
    'to_wallet'                           => 'zur Portokasse',
    'tos_read_and_accepted'               => 'Die Allgemeinen Geschäftsbedingungen PORTOKASSE und INTERNETMARKE habe ich gelesen und akzeptiere diese.',
    'track_id'                            => 'ID für Sendungsverfolgung',
    'use_credentials'                     => 'Zugangsdaten verwenden',
    'voucher_create_time'                 => 'Zeitpunkt der Erstellung',
    'voucher_data'                        => 'Produkt und Ausgabe',
    'voucher_id'                          => 'ID der Marke',
    'voucher_layout'                      => 'Druckformat',
    'voucher_layout_addresszone'          => 'mit Adresse',
    'voucher_layout_frankingzone'         => 'ohne Adresse',
    'voucher_link'                        => 'Marke abrufen',
    'vouchers'                            => 'Internetmarken zu dieser Bestellung',
    'wallet'                              => 'Portokasse',
    'walletform_info'                     => 'Zum Auffüllen Ihrer Portokasse klicken Sie bitte auf den unten stehenden Button.',
    'walletform_submit'                   => 'Portokasse aufladen',
    'wallet_balance_too_low'              => 'Der Ladestand ihrer Portokasse ist zu niedrig für den Abruf einer Internetmarke.',
    'your_wallet_balance'                 => 'Ihr Guthaben',
    'low_wallet_balance'                  => 'Niedrigen Guthabensstand beachten',
    'low_wallet_balance_tooltip'          => 'Wenn aktiviert, werden nur Produkte angezeigt, die mit dem aktuellen Guthabensstand Ihrer Portokasse erworben werden können. Bei Verwendung von Portokasse auf Rechnung (Guthaben kann negativ sein) bitte deaktivieren.',
];
