<?php
/* --------------------------------------------------------------
   afterbuy.lang.inc.php 2023-04-28
   Gambio GmbH
   http://www.gambio.de
   Copyright (c) 2023 Gambio GmbH
   Released under the GNU General Public License (Version 2)
   [http://www.gnu.org/licenses/gpl-2.0.html]
   --------------------------------------------------------------
*/

$t_language_text_section_content_array = [
    'account_token'                            => 'Account-Token',
    'account_token_tooltip'                    => 'Dein Account-Token für die Afterbuy-XML-Schnittstelle im Format xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx (Ziffern 0-9, Buchstaben a-f)',
    'afterbuy_order_id'                        => 'Afterbuy-Vorgangsnummer',
    'all_as_not_paid'                          => '(alle übrigen als nicht bezahlt behandeln)',
    'all_as_paid'                              => '(alle als bezahlt behandeln)',
    'button_send'                              => 'an Afterbuy senden',
    'config_xml_api'                           => 'API-Zugangsdaten',
    'configuration'                            => 'Konfiguration',
    'configuration_orderexport'                => 'Bestellexport',
    'configuration_shop_api'                   => 'Zugangsdaten für Shop-API',
    'cron_note'                                => 'Cronjob',
    'cron_note_text'                           => 'Bitte aktiviere unter Toolbox → Zeitgesteuerte Aufgaben den Afterbuy-Task, um die regelmäßige automatische Übertragung von Bestellungen an Afterbuy zu nutzen. Der regelmäßige Aufruf des in früheren Versionen genutzten separaten Afterbuy-Cronjob-URLs kann dann entfallen.',
    'cron_url'                                 => 'Cronjob-URL',
    'cron_url_tooltip'                         => 'Bitte richten Sie einen Cronjob ein, der die nebenstehende Adresse regelmäßig aufruft. Hierdurch wird die Übertragung der Bestellungen an Afterbuy ausgelöst.',
    'datetime'                                 => 'Zeitpunkt',
    'do_not_change'                            => '(nicht ändern)',
    'do_not_set'                               => '(nicht setzen)',
    'extent_of_import'                         => 'Umfang des Datenimports',
    'import_catalogs'                          => 'Kataloge importieren',
    'import_catalogs_now'                      => 'Kataloge jetzt importieren',
    'import_catalogs_parent_category'          => 'Oberkategorie für Katalogimport',
    'import_catalogs_tooltip'                  => 'Jetzt Afterbuy-Kataloge als Kategorien in den Shop importieren und bereits importierte aktualisieren.',
    'import_configuration'                     => 'Konfiguration für Artikelimport',
    'import_in_progress'                       => 'Import läuft',
    'import_mode_products_import'              => 'vollständige Artikel',
    'import_mode_stocksync'                    => 'nur Bestandsabgleich vorhandene',
    'import_operations'                        => 'Import-Aktionen',
    'import_products'                          => 'Artikel importieren',
    'import_products_dealer_group'             => 'Kundengruppe für Händlerpreise',
    'import_products_default_category'         => 'Standardkategorie bei Artikelimport',
    'import_products_default_category_tooltip' => 'In diese Kategorie werden Artikel importiert, wenn diese bei Afterbuy keinem Katalog zugeordnet sind oder im Shop keine Kategorie für den Katalog vorhanden ist.',
    'import_products_dont_import'              => 'nicht importieren',
    'import_products_level_threshold'          => 'Aktiv-Grenze für Artikel',
    'import_products_level_threshold_tooltip'  => 'Artikel, die bei Afterbuy mit mindestens diesem Zugriffslevel vorliegen, werden als inaktiv importiert.',
    'import_products_now'                      => 'Artikelimport starten/fortsetzen',
    'import_products_restart'                  => 'Zeitpunkt zurücksetzen',
    'import_products_tooltip'                  => 'Der Import von neuen und veränderten Artikeln in den Shop läuft normalerweise im Hintergrund; achte darauf, dass die entsprechende Aktion unter „Zeitgesteuerte Aufgaben“ aktiv ist. Durch das Zurücksetzen des Ausgangszeitpunktes kann eine vollständige Übertragung aller Artikel initiiert werden. Bitte beachte, dass die Zahl der importierten Artikel pro Durchlauf begrenzt ist, bei vielen Artikeln muss der Job also mehrfach laufen, um einen vollständigen Zustand zu erreichen. Mit dem nebenstehenden Button kann sofort ein vollständiger Import (alle nötigen Durchläufe) gestartet werden.',
    'import_starting_from_timestamp'           => 'Importiere Artikel-Änderungen ab',
    'import_tax_class_1'                       => 'Steuerklasse 1',
    'import_tax_class_2'                       => 'Steuerklasse 2',
    'import_tax_class_3'                       => 'Steuerklasse 3',
    'import_tax_class_4'                       => 'Steuerklasse 4',
    'import_tax_class_5'                       => 'Steuerklasse 5',
    'last_sync_datetime'                       => 'Änderungen ab',
    'last_sync_datetime_tooltip'               => 'Beim nächsten Bestandsabgleich werden Artikel berücksichtigt, die nach diesem Zeitpunkt bei Afterbuy verändert wurden. Dieser Wert wird vom Bestandsabgleich automatisch aktualisiert.',
    'last_tracking_sync_tooltip'               => 'Beim nächsten Bestandsabgleich werden Bestellungen berücksichtigt, die nach diesem Zeitpunkt bei Afterbuy verändert wurden. Dieser Wert wird vom Bestandsabgleich automatisch aktualisiert.',
    'logging_level'                            => 'Logging-Level',
    'logging_level_debug'                      => 'debug – sehr ausführlich',
    'logging_level_error'                      => 'error – nur Fehler',
    'logging_level_info'                       => 'info – normale Ereignisse',
    'logging_level_notice'                     => 'notice – signifikante Ereignisse',
    'logging_level_warning'                    => 'warning – problematische Ereignisse',
    'missing_order_id'                         => 'Order ID fehlt und muss mit angegeben werden',
    'module_active'                            => 'Aktiv',
    'order_info_heading'                       => 'Afterbuy',
    'order_info_id'                            => 'Afterbuy-Kundennummer',
    'order_info_success'                       => 'Daten erfolgreich übertragen',
    'order_info_success_no'                    => 'nein',
    'order_info_success_yes'                   => 'ja',
    'order_status'                             => 'Bestellstatus nach Übertragung',
    'order_status_after_tracking_sync_label'   => 'Bestellstatus nach Versand in Afterbuy',
    'order_status_after_tracking_sync_tooltip' => 'Wenn bei Bestellabgleich eine Versand-TrackingID in einer Bestellung gefunden wird, wird die Bestellung im Shop auf den ausgewählten Bestellstatus gesetzt',
    'order_status_not_paid'                    => 'Nicht Bezahlt-Bestellstatus',
    'order_status_not_paid_tooltip'            => 'Bestellung wird als nicht bezahlt übertragen, wenn einer dieser Bestellstatus in der Bestellstatushistorie vorkommt. Mehrfachauswahl: STRG gedrückt halten',
    'order_status_paid'                        => 'Bezahlt-Bestellstatus',
    'order_status_paid_tooltip'                => 'Bestellung wird als bezahlt übertragen, wenn einer dieser Bestellstatus in der Bestellstatushistorie vorkommt. Mehrfachauswahl: STRG gedrückt halten',
    'order_status_set_delivery_date_label'     => 'Versanddatum anhand von Bestellstatus setzen',
    'order_status_set_delivery_date_tooltip'   => 'Beim Exportieren von Bestellungen prüft der Shop, ob der gewählte Bestellstatus in der Bestellstatushistorie vorkommt, und wenn dies der Fall ist, setzt es das Versanddatum zum Zeitpunkt des Setzens des Bestellstatus',
    'order_status_tooltip'                     => 'Bestellstatus nach erfolgreicher Übertragung der Bestelldaten',
    'partner_id'                               => 'Partner ID',
    'partner_id_tooltip'                       => 'Ihre Afterbuy Partner ID',
    'partner_password'                         => 'Partner Passwort',
    'partner_password_tooltip'                 => 'Ihr Partner Passwort für die Afterbuy Shop-Schnittstelle',
    'partner_token'                            => 'Partner-Token',
    'partner_token_tooltip'                    => 'Dein Partner-Token für die Afterbuy-XML-Schnittstelle im Format xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx (Ziffern 0-9, Buchstaben a-f)',
    'product_data_import_mode'                 => 'Modus für Artikeldatenimport',
    'product_import_progress'                  => 'Artikelimport',
    'product_import_start'                     => 'Beginne Artikelimport, bitte warten.',
    'product_import_stop'                      => 'Anhalten',
    'product_import_stopping'                  => 'Wird angehalten …',
    'product_sync_model_anr'                   => 'Artikelnummer (Shop) = Artikelnummer (Afterbuy)',
    'product_sync_model_ean'                   => 'Artikelnummer (Shop) = externe Artikelnummer (Afterbuy)',
    'product_sync_model_prodid'                => 'Artikelnummer (Shop) = ProductId (Afterbuy)',
    'product_sync_pid_anr'                     => 'ProductID (Shop) = Artikelnummer (Afterbuy)',
    'product_sync_pid_ean'                     => 'ProductID (Shop) = externe Artikelnummer (Afterbuy)',
    'product_sync_type'                        => 'Kriterium Artikelabgleich',
    'product_sync_type_tooltip'                => 'Wie werden identische Artikel im Shop und bei Afterbuy identifiziert? Bitte beachte, dass die Werte unbedingt eindeutig sein müssen!',
    'quantity_sync'                            => 'Bestandsabgleich',
    'quantity_sync_info'                       => 'Um regelmäßig die Lagerbestände von Artikeln in deinem Shop mit den bei Afterbuy abzugleichen ohne Artikel aus dem Afterbuy-Bestand zu übernehmen, aktiviere bitte den separaten Vorgang unter Toolbox → Zeitgesteuerte Aufgaben. Bitte beachte, dass der Bestandsabgleich Zusatzoptionen nicht berücksichtigt. Der Bestandsabgleich ist von dem Abgleichskriterium (siehe oben) abhängig. Von einer gleichzeitigen Verwendung von Bestandsabgleich und Artikelimport wird abgeraten.',
    'save_configuration'                       => 'speichern',
    'send_order_details'                       => 'Übermittlung von Bestellungen',
    'send_shipping_info'                       => 'Versandart übertragen',
    'send_shipping_info_never'                 => 'nie',
    'send_shipping_info_initially'             => 'initial',
    'send_shipping_info_always'                => 'immer',
    'send_shipping_info_tooltip'               => 'Die vom Kunden im Checkout gewählte Versandart kann an Afterbuy ins Feld „Versandart“ übertragen.',
    'sent_initial'                             => 'Die Bestellung ist erfolgreich zu Afterbuy übertragen worden.',
    'sent_successfully'                        => 'Erfolgreich übertragen.',
    'sent_unsuccessfully'                      => 'Fehler bei der Übertragung:',
    'sent_update'                              => 'Die Bestellung ist erfolgreich bei Afterbuy aktualisiert worden.',
    'stocksync_configuration'                  => 'Konfiguration für Bestandsabgleich',
    'tracking_sync_description'                => 'Bei Afterbuy eingetragene Versandart',
    'tracking_sync_free_text_placeholder'      => 'Afterbuy Versandart',
    'tracking_sync_label'                      => 'Paketdienst im Shop',
    'tracking_sync_tooltip'                    => 'Sofern in der Afterbuy Bestellung eine Trackingnummer hinterlegt ist und die Versandmethode den Wert des Freifelds entspricht wird beim Synchronisieren der Bestellungen ein Trackinglink im Shop erzeugt.',
    'unauthenticated'                          => 'Nicht authentifiziert!',
    'unknown_order_status'                     => 'Bestellung wurde nicht übertragen, Bestellstatus entspricht weder bezahlt noch unbezahlt Status.',
    'update_quantities'                        => 'Bestandsabgleich',
    'update_quantities_now'                    => 'Bestandsabgleich ausführen',
    'update_quantities_tooltip'                => 'Führt Bestandsableich aus auf Basis der Bestellungen, die seit dem oben konfigurierten Zeitpunkt bei Afterbuy registriert wurden.',
    'use_correctional_items'                   => 'Korrekturposten verwenden',
    'use_correctional_items_tooltip'           => 'Durch unterschiedliche Strategien bei der Rundung der Preise kann es bei Afterbuy zu Abweichungen zwischen Rechnungs- und Zahlbetrag kommen. Mit dieser Option werden Korrekturposten übertragen, um dies auszugleichen',
    'use_separate_tax'                         => 'Mehrwertsteuer getrennt übertragen (B2B)',
    'use_separate_tax_tooltip'                 => 'Bei B2B-Bestellungen mit getrenntem Mehrwertsteuerausweis werden die Artikelposten ohne Steuern übertragen und die Mehrwertsteuer als separater Posten bei Afterbuy angelegt.',
    'user_id'                                  => 'Benutzername',
    'user_id_tooltip'                          => 'Dein Afterbuy-Benutzername, mit dem du dich bei Afterbuy einloggst',
];
