<?php
/* --------------------------------------------------------------
   cashflowtech.lang.inc.php 2019-07-08
   Gambio GmbH
   http://www.gambio.de
   Copyright (c) 2019 Gambio GmbH
   Released under the GNU General Public License (Version 2)
   [http://www.gnu.org/licenses/gpl-2.0.html]
   --------------------------------------------------------------
*/

$t_language_text_section_content_array = [
    'orderextender_title'                       => 'CFT - CashFlowTech - Inkasso',
    'newmandatorinfo_intro'                     => 'Ein effizientes und kundengerechtes Forderungsmanagement ist zeitaufwändig, teuer und kompliziert.
	Ansprüche für den modernen Händler von heute sind vielschichtig und komplex.<br>
	Unsere Inkassodienstleistungen sind darauf ausgelegt, schnell und effektiv Ihre Forderungen zu realisieren.<br>
	Durch unseren professionellen Auftritt wird Ihr Kundenverhältnis nicht belastet und Sie haben mehr Zeit, sich auf Ihr Kerngeschäft zu fokussieren.<br>
	Mit uns haben Sie einen zuverlässigen und erfahrenen Partner an Ihrer Seite. Wir setzen uns für Ihre Belange professionell und effizient ein.<br>',
    'newmandatorinfo_more_info'                 => 'Sie wünschen mehr Informationen?<br>Erfahren Sie mehr unter der Seite.<br>',
    'newmandatorinfo_apply'                     => 'Anmeldung zum Forderungsmanagement',
    'nc_reference_1'                            => '1. Aktenzeichen',
    'nc_reference_2'                            => '2. Aktenzeichen',
    'nc_reference_3'                            => '3. Aktenzeichen',
    'nc_salutation_id'                          => 'Anrede',
    'nc_salutation_id_0'                        => '(keine Anrede)',
    'nc_salutation_id_1'                        => 'Frau',
    'nc_salutation_id_2'                        => 'Herr',
    'nc_salutation_id_3'                        => 'Firma',
    'nc_salutation_id_4'                        => 'Mr.',
    'nc_salutation_id_5'                        => 'Mrs.',
    'nc_title_id'                               => 'Titel',
    'nc_title_id_0'                             => '(keiner)',
    'nc_title_id_2'                             => 'Dr.',
    'nc_title_id_3'                             => 'Prof.',
    'nc_title_id_4'                             => 'Prof. Dr.',
    'nc_title_id_5'                             => 'Dr. med.',
    'nc_title_id_6'                             => 'Dipl.-Ing.',
    'nc_title_id_7'                             => 'Dr. rer. nat.',
    'nc_title_id_8'                             => 'Dr. iur.',
    'nc_title_id_9'                             => 'Mag.',
    'nc_company'                                => 'Unternehmen',
    'nc_company_type_id'                        => 'Rechtsform',
    'nc_company_type_id_0'                      => '(keine/Verbraucher)',
    'nc_company_type_id_1'                      => 'Einzelunternehmen',
    'nc_company_type_id_2'                      => 'Stille Gesellschaft',
    'nc_company_type_id_3'                      => 'OHG',
    'nc_company_type_id_4'                      => 'KG',
    'nc_company_type_id_5'                      => 'GbR (BGB-Gesellschaft)',
    'nc_company_type_id_6'                      => 'AG',
    'nc_company_type_id_7'                      => 'KGaA',
    'nc_company_type_id_8'                      => 'GmbH',
    'nc_company_type_id_9'                      => 'eG',
    'nc_company_type_id_10'                     => 'GmbH & Co. KG',
    'nc_company_type_id_11'                     => 'e.V.',
    'nc_company_type_id_12'                     => 'UG',
    'nc_first_name'                             => 'Vorname',
    'nc_last_name'                              => 'Nachname',
    'nc_maiden_name'                            => 'Geburtsname',
    'nc_street'                                 => 'Straße',
    'nc_housenumber'                            => 'Hausnummer',
    'nc_postalcode'                             => 'PLZ',
    'nc_city'                                   => 'Stadt',
    'nc_country'                                => 'Land',
    'nc_day_of_birth'                           => 'Geburtsdatum',
    'nc_email'                                  => 'E-Mail',
    'nc_phone'                                  => 'Telefon',
    'nc_mobile'                                 => 'Mobil',
    'nc_fax'                                    => 'Telefax',
    'nc_account_number'                         => 'Kontonummer',
    'nc_bank_number'                            => 'BLZ',
    'nc_account_iban'                           => 'IBAN',
    'nc_bank_bic'                               => 'BIC',
    'nc_account_owner_first_name'               => 'Kontoinhaber, Vorname',
    'nc_account_owner_last_name'                => 'Kontoinhaber, Nachname',
    'nc_invoices_to_include'                    => 'Zu übermittelnde Rechnungen',
    'create_new_collection'                     => 'Neuen Vorgang anlegen',
    'base_data'                                 => 'Basisdaten zum Vorgang',
    'base_data_id'                              => 'Vorgangs-ID',
    'base_data_client_id'                       => 'Mandaten-ID',
    'base_data_file_reference'                  => 'Aktenzeichen',
    'base_data_created_at'                      => 'Anlagedatum',
    'base_data_review_at'                       => 'Wiedervorlagedatum',
    'base_data_state_id'                        => 'Status-ID',
    'base_data_state_description'               => 'Status-Beschreibung',
    'base_data_closed_after_state_id'           => 'Vorgang geschlossen nach Status ID',
    'base_data_closed_after_state_description'  => 'Vorgang geschlossen nach Status Beschreibung',
    'detail_data'                               => 'Detaildaten zum Vorgang',
    'detail_data_id'                            => 'Vorgangsdetail-ID',
    'detail_data_file_reference'                => 'Aktenzeichen bei Mandant/Schuldner',
    'detail_data_file_reference_1'              => '1. Aktenzeichen bei Mandant/Schuldner',
    'detail_data_file_reference_2'              => '2. Aktenzeichen bei Mandant/Schuldner',
    'detail_data_file_reference_3'              => '3. Aktenzeichen bei Mandant/Schuldner',
    'detail_data_role'                          => 'Mandant/Schuldner(/weitere Beteiligte)',
    'detail_data_contact_data'                  => 'Daten zu Mandant/Schuldner',
    'detail_data_salutation'                    => 'Anrede',
    'detail_data_first_name'                    => 'Vorname',
    'detail_data_last_name'                     => 'Nachname',
    'detail_data_street'                        => 'Straße',
    'detail_data_housenumber'                   => 'Hausnummer',
    'detail_data_postalcode'                    => 'Postleitzahl',
    'detail_data_city'                          => 'Stadt',
    'detail_data_country'                       => 'Land',
    'bookings'                                  => 'Buchungen',
    'no_bookings'                               => 'keine Buchungen',
    'booking_data'                              => 'Buchungen zum Vorgang',
    'booking_data_id'                           => 'Buchungs-ID (Foko-ID)',
    'booking_data_amount'                       => 'Betrag',
    'booking_data_created_at'                   => 'Buchungs­datum',
    'booking_data_type_id'                      => 'Aufwands­art ID',
    'booking_data_type_description'             => 'Aufwands­art Be­schrei­bung',
    'booking_data_reversal_of_id'               => 'Storno zu Buchungs-ID',
    'reverse_payment_save'                      => 'Storno melden',
    'reverse_payment_amount'                    => 'Storno zu Zahlung, Betrag:',
    'payment_data'                              => 'Zahlungs­auf­teilung',
    'payment_data_id'                           => 'Zahlungs­auf­teilungs-ID',
    'payment_data_amount'                       => 'Betrag (positiv = Storno)',
    'payment_data_created_at'                   => 'Zahlungs­auf­teilungs­datum',
    'payment_data_type_id'                      => 'Aufwandsart ID',
    'payment_data_type_description'             => 'Aufwandsart Be­schrei­bung',
    'payment_data_reversal_of_id'               => 'Storno zu Zahlungs­auf­teilungs-ID',
    'payment_data_booking_id_incoming'          => 'Buchungs-ID des Zahlungs­eingangs',
    'payment_data_booking_id_used'              => 'Buchungs-ID der Forderung (0 = unbekannt)',
    'booking_data_relevant'                     => 'Für Mandant relevante Buchungen zum Vorgang (nur ZE)',
    'booking_data_relevant_id'                  => 'Buchungs-ID (Foko ID)',
    'booking_data_relevant_amount'              => 'Betrag',
    'booking_data_relevant_created_at'          => 'Buchungs­datum',
    'booking_data_relevant_type_id'             => 'Aufwands­art ID',
    'booking_data_relevant_type_description'    => 'Aufwands­art Be­schrei­bung',
    'booking_data_relevant_reversal_of_id'      => 'Storno zu Buchungs-ID (leer = kein Storno)',
    'payment_data_relevant'                     => 'Für Mandant re­le­van­te Zahlungs­auf­teilung',
    'payment_data_relevant_id'                  => 'Zahlungs­auf­teilungs-ID',
    'payment_data_relevant_amount'              => 'Betrag (positiv = Storno)',
    'payment_data_relevant_created_at'          => 'Zahlungs­auf­teilungs­datum',
    'payment_data_relevant_type_id'             => 'Aufwands­art ID',
    'payment_data_relevant_type_description'    => 'Aufwands­art Be­schrei­bung',
    'payment_data_relevant_reversal_of_id'      => 'Storno zu Zahlungs­auf­teilungs-ID',
    'payment_data_relevant_booking_id_incoming' => 'Buchungs-ID des Zahlungs­eingangs',
    'payment_data_relevant_booking_id_used'     => 'Buchungs-ID der Forderung (0 = unbekannt)',
    'new_payment'                               => 'Zahlung zu Vorgang melden',
    'new_payment_amount'                        => 'Betrag',
    'new_payment_type'                          => 'Typ',
    'new_payment_type_610'                      => 'bei Mandant (610)',
    'new_payment_type_600'                      => 'direkt (600)',
    'new_payment_type_620'                      => 'bei Rechtsanwalt (620)',
    'new_payment_save'                          => 'melden',
    'create_collection_ok'                      => 'Vorgang erfolgreich angelegt',
    'create_collection_error'                   => 'Fehler beim Anlegen des Vorgangs',
    'create_payment_ok'                         => 'Zahlung erfolgreich gemeldet',
    'create_payment_error'                      => 'Fehler beim Melden der Zahlung',
    'create_reversal_ok'                        => 'Storno erfolgreich gemeldet',
    'create_reversal_error'                     => 'Fehler beim Melden des Storno',
    'disabled_info'                             => 'Ihr Mandantenkonto wurde deaktiviert. Bitte kontaktieren Sie CashFlowTech für weitere Informationen.',
];

